### Sign up
POST {{host}}/trusted/auth/sign-up
Content-Type: application/json

{
  "username": "aidarsvd",
  "name": "Aidar Chakiev",
  "password": "Chakiev#4"
}


### Sign in
POST {{host}}/trusted/auth/sign-in
Content-Type: application/json

{
  "username": "jdoe",
  "password": "c28d7a2e"
}

### Create user
POST {{host}}/admin/user-create
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhaWRhcnN2ZCIsImV4cCI6MTcyMzk3ODE2MH0.GTlpaRfeaG6gV_NicGoWctxFc7Pu64-7k2mLJGDSsWE

{
  "username": "jdoe",
  "name": "John Doe"
}

### Assign authority to user
POST {{host}}/admin/assign-authority
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhaWRhcnN2ZCIsImV4cCI6MTcyMzk3ODE2MH0.GTlpaRfeaG6gV_NicGoWctxFc7Pu64-7k2mLJGDSsWE

{
  "username": "jdoe",
  "authority": "equipment.delete"
}

### Get user list
GET {{host}}/admin/get-users
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhaWRhcnN2ZCIsImV4cCI6MTcyMzk3ODE2MH0.GTlpaRfeaG6gV_NicGoWctxFc7Pu64-7k2mLJGDSsWE

### Deactivaye user
POST {{host}}/admin/delete-user
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhaWRhcnN2ZCIsImV4cCI6MTcyMzk3ODE2MH0.GTlpaRfeaG6gV_NicGoWctxFc7Pu64-7k2mLJGDSsWE

username = jdoe


### Activate user
POST {{host}}/admin/activate-user
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhaWRhcnN2ZCIsImV4cCI6MTcyMzk3ODE2MH0.GTlpaRfeaG6gV_NicGoWctxFc7Pu64-7k2mLJGDSsWE

username = jdoe

### Equipment create
POST {{host}}/equipment/create
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhaWRhcnN2ZCIsImV4cCI6MTcyMzk3ODE2MH0.GTlpaRfeaG6gV_NicGoWctxFc7Pu64-7k2mLJGDSsWE

{
  "model": "GPS Modules"
}

### Equipment get
GET {{host}}/equipment/get-list?s=f
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhaWRhcnN2ZCIsImV4cCI6MTcyMzk3ODE2MH0.GTlpaRfeaG6gV_NicGoWctxFc7Pu64-7k2mLJGDSsWE